# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/tensorboard/"
  name: resnet50
  log_graph: True
  default_hp_metric: True
  prefix: ""
  # version: ""
